// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsGm7Oc4pDiFgUiDF_47YA5TVnZu3EFmM',
    appId: '1:100584185973:web:05a056818b1e97b5cb583c',
    messagingSenderId: '100584185973',
    projectId: 'appuser-thesis',
    authDomain: 'appuser-thesis.firebaseapp.com',
    storageBucket: 'appuser-thesis.firebasestorage.app',
    measurementId: 'G-7PBDG47QX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pXeZ16ndholUy__aoDxFz9HtaZnDx1k',
    appId: '1:100584185973:android:39a72845cee102adcb583c',
    messagingSenderId: '100584185973',
    projectId: 'appuser-thesis',
    storageBucket: 'appuser-thesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCkZ0cNifYdgiomwfwNOr3oIyi5mHUnXs',
    appId: '1:100584185973:ios:d33ec1e365d591a1cb583c',
    messagingSenderId: '100584185973',
    projectId: 'appuser-thesis',
    storageBucket: 'appuser-thesis.firebasestorage.app',
    iosBundleId: 'com.example.appUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCkZ0cNifYdgiomwfwNOr3oIyi5mHUnXs',
    appId: '1:100584185973:ios:d33ec1e365d591a1cb583c',
    messagingSenderId: '100584185973',
    projectId: 'appuser-thesis',
    storageBucket: 'appuser-thesis.firebasestorage.app',
    iosBundleId: 'com.example.appUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsGm7Oc4pDiFgUiDF_47YA5TVnZu3EFmM',
    appId: '1:100584185973:web:7f0870d55f0fd57acb583c',
    messagingSenderId: '100584185973',
    projectId: 'appuser-thesis',
    authDomain: 'appuser-thesis.firebaseapp.com',
    storageBucket: 'appuser-thesis.firebasestorage.app',
    measurementId: 'G-FF6LP0FZFW',
  );
}
